#!/bin/bash

python train.py --dataset SMD --group 1-1 --epochs 10
python train.py --dataset SMD --group 1-2 --epochs 10
python train.py --dataset SMD --group 1-3 --epochs 10
python train.py --dataset SMD --group 1-4 --epochs 10
python train.py --dataset SMD --group 1-5 --epochs 10
python train.py --dataset SMD --group 1-6 --epochs 10
python train.py --dataset SMD --group 1-7 --epochs 10
python train.py --dataset SMD --group 1-8 --epochs 10
python train.py --dataset SMD --group 2-1 --epochs 10
python train.py --dataset SMD --group 2-2 --epochs 10
python train.py --dataset SMD --group 2-3 --epochs 10
python train.py --dataset SMD --group 2-4 --epochs 10
python train.py --dataset SMD --group 2-5 --epochs 10
python train.py --dataset SMD --group 2-6 --epochs 10
python train.py --dataset SMD --group 2-7 --epochs 10
python train.py --dataset SMD --group 2-8 --epochs 10
python train.py --dataset SMD --group 2-9 --epochs 10
python train.py --dataset SMD --group 3-1 --epochs 10
python train.py --dataset SMD --group 3-2 --epochs 10
python train.py --dataset SMD --group 3-3 --epochs 10
python train.py --dataset SMD --group 3-4 --epochs 10
python train.py --dataset SMD --group 3-5 --epochs 10
python train.py --dataset SMD --group 3-6 --epochs 10
python train.py --dataset SMD --group 3-7 --epochs 10
python train.py --dataset SMD --group 3-8 --epochs 10
python train.py --dataset SMD --group 3-9 --epochs 10
python train.py --dataset SMD --group 3-10 --epochs 10
python train.py --dataset SMD --group 3-11 --epochs 10